### ISSUE TITLE
Inquiry About Merging the TensorRT Branch

### ISSUE THREAD

**Issue by mjason** [ankane/onnxruntime-ruby#10]
I see there is a branch: tensor-rt that added TensorRT support, but it hasn't been merged. May I ask if there are any issues encountered? And is there an ETA for when it may be merged? Thank you.

**Comment by ankane** [comment]
Hi @mjason, I spent some time on it this weekend, but wasn't able to get it working with all the tests. Was running into the following error (both with and without a custom logger).

```text
OnnxRuntime::Error: /onnxruntime_src/include/onnxruntime/core/common/logging/logging.h:294 static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger() Attempt to use DefaultLogger but none has been registered.
```

Happy to review a PR if someone is able to figure it out.
